name: "continuous integration test"
on:
  push:
    branches: [ main, development ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/cffvalidation.yml'
      - '.github/workflows/release.yml'
      - '.github/zenodo/*'
  pull_request:
    branches: [ main, development ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/cffvalidation.yml'
      - '.github/workflows/release.yml'
      - '.github/zenodo/*'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "checkout"
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

