### github action to publish a debug
##
name: "debug"

## Controls when the workflow will run
on:
  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  debug:
    name: "debug"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

        ## opening a debug console
      - name: Setup upterm session
        env:
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
