name: create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to register (e.g. '1.0.1' or '2023.03')"
        required: true

env:
  VERSION_SCHEMA: semantic # 'semantic' or 'calendar'
  REPO_NAME: unnamed # provide repository name: https://github.com/railtoolkit/REPO_NAME
  ZENODO_COLLECTION: # provide Zenodo collection number $COLLECTION from DOI: 10.5281/zenodo.COLLECTION

jobs:
  version:
    name: "check submitted version"
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.version_check.outputs.current }}
      new: ${{ steps.version_check.outputs.new }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "check if repo has appropriate metadata"
        run: |
          TITLE_CITATION=$(grep '^title:' CITATION.cff | cut -d' ' -f2)
          TITLE_ZENODO=$(grep -m 1 '"title":' .github/zenodo/metadata.json | cut -d'"' -f4)
          if [[ $TITLE_CITATION -eq "PROJEKT_TEMPLATE" ]]; then
            echo "- :no_entry_sign: The file 'CITATION.cff' has no appropriate!" >> $GITHUB_STEP_SUMMARY
            echo "- :warning: Please modify CITATION.cff to reflect the metadata of the project." >> $GITHUB_STEP_SUMMARY
            exit 1
          elif [[ $TITLE_ZENODO -eq "PROJEKT_TEMPLATE" ]]; then
            echo "- :no_entry_sign: The file '.github/zenodo/metadata.json' has no appropriate!" >> $GITHUB_STEP_SUMMARY
            echo "- :warning: Please modify metadata.json to reflect the metadata of the project." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: "check version number"
        id: version_check
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Version to register '$VERSION':"  >> $GITHUB_STEP_SUMMARY
          ## =================================
          ## check if version follows the semantic version pattern
          ## ---------------------------------
          #remove a trailing 'v' if it exists
          if [[ ${VERSION:0:1} -eq "v" ]]; then
            VERSION=${VERSION:1}
          fi
          # check with regular expressions
          STATUS=0
          VER_REGEX="a^"
          if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
            VER_REGEX="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$"
          fi
          if [[ $VERSION_SCHEMA -eq "calendar" ]]; then
            VER_REGEX="^([0-9]{4}).(1[0-2]|0[1-9])$"
          fi
          if [[ ! $VERSION =~ $VER_REGEX ]]; then
            STATUS=1
          fi
          if [ $STATUS = 1 ]; then
            echo "- :no_entry_sign: format does not follow a versioning schema" >> $GITHUB_STEP_SUMMARY
            if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
              echo ":warning: Please see https://semver.org/ for further information." >> $GITHUB_STEP_SUMMARY
            elif [[ $VERSION_SCHEMA -eq "calendar" ]]; then
              echo ":warning: Please see https://calver.org/ for further information." >> $GITHUB_STEP_SUMMARY
            fi
            exit 1
          else
            if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
              echo "- follows the semantic versioning schema format :white_check_mark:" >> $GITHUB_STEP_SUMMARY
            elif [[ $VERSION_SCHEMA -eq "calendar" ]]; then
              echo "- follows the calendar versioning schema format :white_check_mark:" >> $GITHUB_STEP_SUMMARY
            fi
          fi
          ## =================================
          ## check if version is an increment
          ## ---------------------------------
          CURRENT_VERSION=$(grep -n -m 1 "## Version \[*.*.*\]" CHANGELOG.md | cut -d[ -f2 | cut -d] -f1)
          if [ "$CURRENT_VERSION" = "" ]; then
            CURRENT_VERSION=no_version
            echo "- :warning: no previous version available" >> $GITHUB_STEP_SUMMARY
          else
            VERSION_MAJOR=$(echo $VERSION | cut -d. -f1 )
            VERSION_MINOR=$(echo $VERSION | cut -d. -f2 )
            CURRENT_VERSION_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1 )
            CURRENT_VERSION_MINOR=$(echo $CURRENT_VERSION | cut -d. -f2 )
            if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
              VERSION_PATCH=$(echo $VERSION | cut -d. -f3 )
              CURRENT_VERSION_PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 )
              if [[ $VERSION_MAJOR -eq CURRENT_VERSION_MAJOR ]]; then
                if [[ $VERSION_MINOR -eq CURRENT_VERSION_MINOR ]]; then
                  if [[ $(($VERSION_PATCH - 1)) -ne CURRENT_VERSION_PATCH ]]; then
                    STATUS=1
                  fi
                else
                  if [[ $(($VERSION_MINOR - 1)) -eq CURRENT_VERSION_MINOR ]]; then
                    if [[ $VERSION_PATCH -ne 0 ]]; then
                      STATUS=1
                    fi
                  else
                    STATUS=1
                  fi
                fi
              else
                if [[ $(($VERSION_MAJOR - 1)) -eq CURRENT_VERSION_MAJOR ]]; then
                  if [[ $VERSION_MINOR -ne 0 ]]; then
                    STATUS=1
                  fi
                  if [[ $VERSION_PATCH -ne 0 ]]; then
                    STATUS=1
                  fi
                else
                  STATUS=1
                fi
              fi
            elif [[ $VERSION_SCHEMA -eq "calendar" ]]; then
              if [[ $VERSION_MAJOR -eq CURRENT_VERSION_MAJOR ]]; then
                if [[ ! $VERSION_MINOR -gt CURRENT_VERSION_MINOR ]]; then
                  STATUS=1
                fi
              elif [[ $VERSION_MAJOR -lt CURRENT_VERSION_MAJOR ]]; then
                STATUS=1
              fi
            fi
            if [ $STATUS = 1 ]; then
              if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
                echo "- :no_entry_sign: Version skipped steps from the previous version $CURRENT_VERSION and thus does not follow the semantic versioning schema." >> $GITHUB_STEP_SUMMARY
                echo "- :warning: Please see https://semver.org/ for further information." >> $GITHUB_STEP_SUMMARY
              elif [[ $VERSION_SCHEMA -eq "calendar" ]]; then
                echo "- :no_entry_sign: Version is not higher then the previous version $CURRENT_VERSION and thus does not follow the calendar versioning schema." >> $GITHUB_STEP_SUMMARY
                echo "- :warning: Please see https://calver.org/ for further information." >> $GITHUB_STEP_SUMMARY
              fi
              exit 1
            else
              echo "- is an increment from the previous version :white_check_mark:" >> $GITHUB_STEP_SUMMARY
            fi
          fi

          ## =================================
          ## provide variables for subsequent jobs
          ## ---------------------------------
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "new=$VERSION" >> $GITHUB_OUTPUT

  create_package:
    name: "create package"
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Creating package and release note for '${{ needs.version.outputs.new }}':" >> $GITHUB_STEP_SUMMARY

      # 1. checkout the repo
      - name: "checkout"
        uses: actions/checkout@v3

      # 2. create release note
      - name: "create release note"
        run: |
          NEW_VERSION=${{ needs.version.outputs.new }}
          CURRENT_VERSION=${{ needs.version.outputs.current }}
          STATUS=0
          ## =================================
          ## create release note
          ## ---------------------------------
          TOP=$(grep -n "## \[Unreleased\]" CHANGELOG.md | cut -d: -f1)
          if [ "$CURRENT_VERSION" = "no_version" ]; then
            BOTTOM=$(grep -n -m 1 "\[Unreleased\]: https://github.com/railtoolkit/" CHANGELOG.md | cut -d: -f1)
          else
            BOTTOM=$(grep -n -m 1 "## Version \[$CURRENT_VERSION\]" CHANGELOG.md | cut -d: -f1)
          fi
          awk "NR>$TOP&&NR<$BOTTOM" CHANGELOG.md > release-note-v$NEW_VERSION.md
          sed -i -- "s/###/##/g" release-note-v$NEW_VERSION.md
          ## =================================
          ## check if release note is empty
          ## ---------------------------------
          WORD_COUNT=$(wc -w release-note-v$NEW_VERSION.md | awk '{print $1}')
          if [[ $WORD_COUNT -lt 4 ]]; then
            STATUS=1
          fi
          if [ $STATUS = 1 ]; then
            echo "- :no_entry_sign: 'Unreleased' section in CHANGELOG.md is empty" >> $GITHUB_STEP_SUMMARY
            echo ":warning: Please provide a meaningful CHANGELOG.md for the new version $NEW_VERSION." >> $GITHUB_STEP_SUMMA
            exit 1
          else
            echo "- 'Unreleased' section in CHANGELOG.md has content :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          fi
          ## =================================
          ## remove empty lines from top and bottom
          ## ---------------------------------
          sed -i -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}' release-note-v$NEW_VERSION.md

      # 3. create release archive
      ## exclude certain files from release archive
      - run: |
          LS=$(ls)
          FILES=()
          for ITEM in $LS; do
            if [[ ! $ITEM = "CHANGELOG.md" ]] &&
               [[ ! $ITEM = "CITATION.cff" ]] &&
               [[ ! $ITEM = "CODE_OF_CONDUCT.md" ]] &&
               [[ ! $ITEM = "CONTRIBUTING.md" ]]; then
              FILES=${FILES:+$FILES }$ITEM
            fi
          done
      - name: "create release archive"
        uses: papeloto/action-zip@v1.1
        with:
          files: $FILES
          recursive: false
          dest: $REPO_NAME-v${{ needs.version.outputs.new }}.zip
      - run: echo "- creating ZIP-Archive for the new release :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # 4. upload artifact to share it with other jobs
      - uses: actions/upload-artifact@v3
        with:
          path: |
            release-note-v${{ needs.version.outputs.new }}.md
            $REPO_NAME-v${{ needs.version.outputs.new }}.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      - run: echo "- providing ZIP-Archive and release notes for other jobs :white_check_mark:" >> $GITHUB_STEP_SUMMARY

  publish_github:
    needs: [create_package, version]
    name: "publish on github"
    runs-on: ubuntu-latest
    steps:
      # 1. download artifact in folder artifact/
      - uses: actions/download-artifact@v3

      # 2. creating a new release
      - name: "create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: artifact/release-note-v${{ needs.version.outputs.new }}.md
          draft: false
          prerelease: false

      # 3. upload package to new release
      - name: "upload release asset"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/$REPO_NAME-v${{ needs.version.outputs.new }}.zip
          asset_name: $REPO_NAME-v${{ needs.version.outputs.new }}.zip
          asset_content_type: application/zip

      # 4. publish release on github
      - name: "publish release"
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}

  zenodo:
    needs: [create_package, version]
    name: "publish on zenodo"
    outputs:
      doi: ${{ steps.zenodraft.outputs.doi }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Archiving package on zenodo to get a DOI:" >> $GITHUB_STEP_SUMMARY
      # 1. download artifact in folder artifact/ and move it one level up and checkout the repo
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: |
          mv ./artifact/$REPO_NAME-v${{ needs.version.outputs.new }}.zip ./
          echo "- getting ZIP-Archive and release notes :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # 2. install zenodraft
      - name: "install zenodraft"
        env:
          URL: "https://zenodo.org/"
        run: |
          STATUS=0
          npm install -g zenodraft
          echo "- installing zenodraft :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          if ! curl --output /dev/null --silent --head --fail "$URL"; then
            STATUS=1
          fi
          if [ $STATUS = 1 ]; then
            echo "- :no_entry_sign: $URL is not reachable" >> $GITHUB_STEP_SUMMARY
            echo ":warning: Please re-run action later!" >> $GITHUB_STEP_SUMMARY
            echo ":warning: Please remove github release manually!" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "- $URL is reachable :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          fi

      # 3. Update zenodo metadata.json
      - name: "Update zenodo metadata.json"
        run: |
          VERSION=${{ needs.version.outputs.new }}
          sed -i".backup" -e"s/\"version\": \"%%\[SCRIPT\]\"/\"version\": \"$VERSION\"/g" .github/zenodo/metadata.json
          echo "- updating zenodo metadata :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # 4. upload new release to zenodo
      - name: "uploading to zenodo"
        id: zenodraft
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
        run: |
          DOI=$(zenodraft deposition create version $ZENODO_COLLECTION)
          zenodraft file add $DOI $REPO_NAME-v*.zip
          zenodraft metadata update $DOI .github/zenodo/metadata.json
          zenodraft deposition publish $DOI
          ## =================================
          ## provide variables for subsequent jobs
          ## ---------------------------------
          echo "doi=10.5281/zenodo.$DOI" >> $GITHUB_OUTPUT
          echo "- publish release at zenodo with DOI: 10.5281/zenodo.$DOI :white_check_mark:" >> $GITHUB_STEP_SUMMARY

  update_repository:
    needs: [zenodo, version]
    name: "updating CITATION.cff and CHANGELOG.md"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating CITATION.cff and CHANGELOG.md:" >> $GITHUB_STEP_SUMMARY
      # 1. checkout the repo
      - name: "checkout"
        uses: actions/checkout@v3
        # with:
        #   ref: main

      # 2. update CITATION.cff
      - name: "update CITATION.cff"
        run: |
          DATE=$(date "+%Y-%m-%d")
          VERSION=${{ needs.version.outputs.new }}
          DOI=${{ needs.publish_zenodo.outputs.doi }}
          echo "find lines in CITATION.cff"
          VERSION_LINE=$(grep -n '^version:' CITATION.cff | cut -d: -f1)
          DATE_LINE=$(grep -n '^date-released:' CITATION.cff | cut -d: -f1)
          echo "select the second DOI"
          DOI_LINE=$(grep -n 'type: doi' CITATION.cff | cut -d: -f1 | awk "NR==2")
          DOI_LINE=$(( $DOI_LINE + 1 ))
          echo "update CITATION.cff"
          sed -i -- "${VERSION_LINE}s|.*|version: $VERSION|" CITATION.cff
          sed -i -- "${DATE_LINE}s|.*|date-released: ${DATE}|" CITATION.cff
          sed -i -- "${DOI_LINE}s|.*|    value: $DOI|" CITATION.cff
          echo "- updated CITATION.cff :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # 3. update CHANGELOG.md
      - name: "update CHANGELOG.md"
        run: |
          DATE=$(date "+%Y-%m-%d")
          VERSION=${{ needs.version.outputs.new }}
          URL="https://github.com/railtoolkit/$REPO_NAME"
          CURRENT_VERSION=${{ needs.version.outputs.current }}
          if [[ $VERSION_SCHEMA -eq "semantic" ]]; then
            sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION] $DATE" CHANGELOG.md
          elif [[ $VERSION_SCHEMA -eq "calendar" ]]; then
            sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION]" CHANGELOG.md
          fi
          if [ "$CURRENT_VERSION" = "no_version" ]; then
            sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/releases/tag/v$VERSION|" CHANGELOG.md
          else
            sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/compare/v$CURRENT_VERSION...v$VERSION|" CHANGELOG.md
          fi
          echo "- updated CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY

      # 4. push the change back to main
      - name: push
        uses: EndBug/add-and-commit@v9
        with:
          message: "updated to ${{ needs.version.outputs.new }} (via github action)"
          add: CITATION.cff CHANGELOG.md
          author_name: railtoolkit
          author_email: railtoolkit@ownx.net
          tag: 'v${{ needs.version.outputs.new }} --force'
      - run: echo "- updated repository with new CITATION.cff and CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY

  publish_mastodon:
    needs: [zenodo, version]
    name: "Toot about it on fosstodon.org"
    runs-on: ubuntu-latest
    steps:
      - uses: cbrgm/mastodon-github-action@v1
        with:
          message: "The new version ${{ needs.version.outputs.new }} of $REPO_NAME is available! DOI: https://doi.org/${{ needs.zenodo.outputs.doi }}."
          visibility: "public" # default: public
        env:
          MASTODON_URL: "https://fosstodon.org/"
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
